### PR TITLE
Added stripe payment

### PR DESCRIPTION
**Pull request by americanoame**
added dotenv to start the stripe payment process

### CODE REVIEW

**Comment by americanoame** [comment]
added dotenv to start the stripe payment process

**Review by americanoame — COMMENTED** [review]
Screenshot 2024-03-22 at 3 20 40 AM
Screenshot 2024-03-22 at 3 22 04 AM
Screenshot 2024-03-22 at 3 26 40 AM

**Comment by americanoame** [comment]
the payment pages process step by step

**Review by americanoame — COMMENTED** [review]
Screenshot 2024-03-22 at 3 27 26 AM
Screenshot 2024-03-22 at 3 30 02 AM

**Comment by americanoame** [comment]
the success  and failed pages

**Comment by DaimsKlarou** [comment]
test

**Pull request closed without merging**
